{"name": "test_bug_link", "status": "passed", "attachments": [{"name": "stdout", "source": "51926677-0d5a-43ad-b406-f7937e126493-attachment.txt", "type": "text/plain"}], "start": 1637130854773, "stop": 1637130854773, "uuid": "3f0fda84-df4e-4acf-ae90-ab2b9f86d99b", "historyId": "87540aa06a43626bd5f25151387a5c08", "testCaseId": "63f69928beb8d29055af0649c3890aef", "fullName": "test_allure_link_issue#test_bug_link", "labels": [{"name": "suite", "value": "test_allure_link_issue"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "7572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_link_issue"}], "links": [{"type": "issue", "url": "http://www.mytesttracker.com/issue140", "name": "这是一个issue"}]}